spring.datasource.url=jdbc:postgresql://localhost:5432/blueprintsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Profile specific properties

# Sin filtro (por defecto)
# No especificar nada o dejar comentado

# Filtro de redundancia
# spring.profiles.active=redundancy

# Filtro de undersampling  
# spring.profiles.active=undersampling